### ISSUE TITLE
Over 40 Web Clubへの入会方法が分かりません

### ISSUE THREAD

**Issue by mendelssohnbach** [pitang1965/over40webclub-tos#6]
URL https://over40webclub.netlify.app/

の「ご連絡お待ちしています」をクリックし、
Twitterのピータン@Over 40 Web Clubに遷移しました。

1. Messageアイコンをクリック
2. メッセージを作成をクリック

と操作しましたが、虫眼鏡アイコン付きの「ユーザを検索」と表示されます。
メッセージが入力できません。

入会のための操作方法をご教示ねがいます。

**Comment by pitang1965** [comment]
こんにちは。お手数をおかけして申し訳ございません。
興味持っていただきありがとうございます。40歳以上の方ならご参加頂けます。
Twitterアカウントを持っている方が、Twitterで私にメッセージを送っていただき、そこで私がメールアドレスを訪ね、招待メールを送るということでやってきていました。
もしも、Twitterをやられていないのでしたら、pitang1965@gmail.com までご連絡ください。

サイトのほう、お問い合わせフォームとか別の方法を考えるべきかもしれません。

ご連絡ありがとうございます。

**Comment by mendelssohnbach** [comment]
お忙しい中、連絡をありがとうございます。

Twitterアカウントは持っているが、使い方がググってもわからない。

私のような初心者の域にすら達していない者でもよろしければ、
入会を希望します。


2021年1月15日(金) 10:20 Pitang1965 <notifications@github.com>:

**Comment by pitang1965** [comment]
ダイレクトメッセージの送信方法は"Twitter ダイレクトメッセージ"でGoogle検索できます。
https://help.twitter.com/ja/using-twitter/direct-messages

**Comment by mendelssohnbach** [comment]
回答ありがとうございます。
無事に入会することができました。

Issueをクローズします。
